# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'XXPagingScrollView' do

pod "SnapKit"

end

target 'XXPagingScrollViewTests' do

end

